version: '3'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=examplepass
      - MYSQL_DATABASE=demodb
      - MYSQL_REPLICA_USER=replica
      - MYSQL_REPLICA_PASS=replica_Passw0rd
    volumes:
      - ./datavolume:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
      - ./db/replica:/docker-entrypoint-initdb.d/
  web:
    image: mezzaninedocker_web
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static:/static
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./static:/static
      - ./nginx/config:/etc/nginx/conf.d

