version: '3'
services:
  db:
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD="examplepass"
      - MYSQL_DATABASE=demodb
      - MYSQL_USER=one
      - MYSQL_PASSWORD=onepwd
    volumes:
      - ./datavolume:/var/lib/mysql
  web:
    restart: always
    image: mezzaninedocker_web
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
  nginx:
    restart: always
    image: mezzaninedocker_nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - web:web
    deploy:
      mode: global
