version: '2'
services:
  slave:
    build: ./db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./db/conf:/etc/mysql/conf.d:z
    env_file: ./db/db.env
  web:
    restart: always
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:z
    expose:
      - "8000"
    depends_on:
      - slave
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:z
    volumes_from:
      - web
    links:
      - web:web
