version: '2'
services:
  db:
    restart: always
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD="examplepass"
      - MYSQL_DATABASE=demodb
      - MYSQL_USER=one
      - MYSQL_PASSWORD=onepwd
    volumes:
      - ./datavolume:/var/lib/mysql:z
  web:
    restart: always
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:z
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:z
    volumes_from:
      - web
    links:
      - web:web
